Fix compatibility with GCC 8
GCC before 11.2 causes a compilation failure due to an incompatibility
between libc++ and libstdc++:

abigail_reader.cc:586:75: error: ‘class std::basic_ostream<char>’ has no member named ‘str’

By expanding the statements a little such that .str() is not applied on the
return type of operator<< this can be mitigated.

Link: http://cplusplus.github.io/LWG/lwg-defects.html#1203
Reported-by: Mark Wielaard <mark@klomp.org>
PiperOrigin-RevId: 474244988
Change-Id: Ibe73c836b9e49d461e16865204f00ed06f6b27c8